<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Robot 2.0</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</head>
<body>
    <header class="container-fluid"><h1 class="h1 text-center">Robot2.0</h1></header>
    <br>
    <main class="container">
    <?php if (empty($_POST)) { ?>
    <form method="POST">
        <label for="name">Identifiant de votre robot</label>
        <input type="text" name="name" placeholder="XX-1234" pattern="[A-Z]{2}-[0-9]{4}"> 
        <label for="guessNum">Nombre à deviner (entre 1 et 1000)</label>
        <input type="number" min="1" max="1000" name="guessNum" placeholder="1-1000">
        <label for="alignment">Alignement</label>
        <select name="alignment" id="alignment">
            <option value="">--Choisissez un alignement--</option>
            <option value="random">Aléatoire</option>
            <option value="good">Bon</option>
            <option value="evil">Mauvais</option>
        </select>            
        <button type="submit">Go!</button>
    </form>
    <?php } 
    
    if ($_POST) { 
        require("../index.php"); ?>
      
    <form method="POST">
        <input type="hidden" name="name">
        <input type="hidden" name="guessNum">
        <input type="hidden" name="alignment" value="random">
        <button type="submit">Regenerate!</button>
    </form>
        
    <?php
    }
    ?>
    </main>
</body>
</html>